name: Bug Report
description: Something isn't working as expected
labels: ["bug", "needs-triage"]
body:
  - type: input
    id: component
    attributes:
      label: Component / Hook
      placeholder: e.g. MagneticCard, useSpringGrid
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug clearly
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Import component
        2. Pass these props...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Aurae version
      placeholder: e.g. 0.1.0
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser (if visual bug)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
